/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/page/': RouteRecordInfo<'/page/', '/page', Record<never, never>, Record<never, never>>,
    '/page/other-page/': RouteRecordInfo<'/page/other-page/', '/page/other-page', Record<never, never>, Record<never, never>>,
    '/page/sub-page-1/': RouteRecordInfo<'/page/sub-page-1/', '/page/sub-page-1', Record<never, never>, Record<never, never>>,
    '/page/sub-page-2/': RouteRecordInfo<'/page/sub-page-2/', '/page/sub-page-2', Record<never, never>, Record<never, never>>,
    '/page-2/': RouteRecordInfo<'/page-2/', '/page-2', Record<never, never>, Record<never, never>>,
  }
}
